---
title: "Appendix 1 Title"
subtitle: "Subtitle"
running-head: "Appendix 1"
author:
  - name: Gregory N. Nishihara
    affiliation:
      - ref: 1
      - ref: 2
  - name: Yukio Inoue
    affiliation:
      - ref: 3
affiliations:
  - id: 1
    name: Nagasaki University
    department: Organization for Marine Science and Technology
    region: Nagasaki
    country: Japan
    postal-code: 852-8521
  - id: 2
    name: Nagasaki University
    department: Institute for East China Sea Research
    region: Nagasaki
    country: Japan
    postal-code: 851-2213
  - id: 3
    name: Nagasaki University
    department: Graduate School of Fisheries and Environmenal Science
    region: Nagasaki
    country: Japan
    postal-code: 852-8521
format: 
  appendix-typst:
    figprefix: A1
    margin:
      top: 4cm
      bottom: 2cm
      y: 3cm
fig-width: 8
fig-height: 5
bibliography: references.bib
execute:
  echo: false
  message: false
  warning: false
---

# Introduction

{{< lipsum 1 >}}

## Example figure

```{r}
library(tidyverse)
library(ggpubr)
library(ggtext)
library(magick)
library(patchwork)
library(showtext)
library(tinytable)
```

```{r}
font_add_google(family = "notosans", "Noto Sans")
theme_pubr(base_family = "notosans", base_size = 10) |> theme_set()
theme_replace(
  panel.background = element_rect(fill = "white", color = "black", linewidth = 1),
  axis.line.x = element_blank(),
  axis.line.y = element_blank(),
  axis.title.x = element_markdown(family = "notosans", lineheight = 1.5, margin = unit(c(0.5,0,0,0), "lines")),
  axis.title.y = element_markdown(family = "notosans", angle = 90, linewidth = 1.5, margin = unit(c(0,0.5,0,0), "lines")),
  legend.background = element_blank(),
  legend.title = element_markdown(family = "notosans"),
  legend.text = element_markdown(family = "notosans", size = 1)
) 
showtext_auto()
```

```{r}
#| label: fig-figure
#| fig-cap: A histogram of 100 values sampled from a standard normal distribution.

data = tibble(Values = rnorm(100))
ggplot(data) + 
  geom_histogram(aes(x = Values))
```

### Example table

```{r}
#| label: tbl-table
#| tbl-cap: A sample of the  Iris data set.

iris |> 
  group_by(Species) |> 
  slice_sample(n = 3) |>
  select(Species, matches("Petal")) |> 
  mutate(Species= str_glue("Iris {Species}")) |> 
  rename_with(~c("Species", "Petal length (cm)", "Petal width (cm)")) |> 
  tt() |> 
  style_tt(i = 1:15, j = 2:3, align = "r") |> 
  style_tt(i = 1:15, j = 1, italic = TRUE)

```



# More Information

You can learn more about creating custom Typst templates here: 

<https://quarto.org/docs/prerelease/1.4/typst.html#custom-formats>

Some references to read.

* @fujita_seaweed_2023
* @hurd_forensic_2022
* @pessarrodona_carbon_2023
* @rose_methods_2023
* @ross_potential_2023
* @zhang_atmospheric_2023
* @hurd_airsea_2024
* @kim_harnessing_2024
* @moreda_role_2024
* @nardelli_primary_2024
* @smith_state_2023
* @duarte_carbon_2025
